services:
  portfolio:
    image: ${DOCKERHUB_IMAGE}
    container_name: portfolio_website
    restart: unless-stopped
    networks:
      - cloudflare-tunnel-net
    environment:
      - APP_ENV=${APP_ENV}

networks:
  cloudflare-tunnel-net:
    external: true
