services:
  portfolio:
    image: ${DOCKERHUB_IMAGE}
    container_name: portfolio_website
    restart: unless-stopped
    networks:
      - nginx-proxy-net
    environment:
      - APP_ENV=${APP_ENV}

networks:
  nginx-proxy-net:
    external: true
