services:
  blog:
    image: ${DOCKERHUB_IMAGE}
    container_name: homelab_blog
    restart: unless-stopped
    networks:
      - nginx-proxy-net
    expose:
      - "80"

networks:
  nginx-proxy-net:
    external: true
