services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - "80"
      - "443"
    environment:
      TZ: "Europe/London"
      FTLCONF_webserver_api_password: ${WEB_PASSWORD}
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - "etc-pihole:/etc/pihole"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
    networks:
      nginx-proxy-net:

volumes:
  etc-pihole:

networks:
  nginx-proxy-net:
    external: true
