version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_daemon
    restart: always
    command: tunnel run --token ${TUNNEL_TOKEN}
    networks:
      - cloudflare-tunnel-net

networks:
  cloudflare-tunnel-net:
    external: true
