version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - cloudflare-tunnel-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites:/etc/nginx/sites-enabled:ro
      - ./logs:/var/log/nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_daemon
    restart: unless-stopped
    command: tunnel run --token ${TUNNEL_TOKEN}
    networks:
      - cloudflare-tunnel-net

networks:
  cloudflare-tunnel-net:
    external: true
