version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - cloudflare-tunnel-net
    volumes:
      - ../../config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../config/nginx/sites:/etc/nginx/sites-enabled:ro
      - ../../logs/nginx:/var/log/nginx
    ports:
      - "80:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_daemon
    restart: unless-stopped
    command: tunnel run --token ${TUNNEL_TOKEN}
    networks:
      - cloudflare-tunnel-net

networks:
  cloudflare-tunnel-net:
    external: true
