version: "3.8"
services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing-server
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${SYNCTHING_DIR}/config:/var/syncthing/config
      - ${SYNCTHING_DIR}/data:/var/syncthing/data
    ports:
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    expose:
      - "8384"
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    expose:
      - "80"
    volumes:
      - ${SYNCTHING_DIR}/data:/srv
      - ${FILEBROWSER_DIR}/database.db:/database.db
    restart: unless-stopped
    networks:
      - nginx-proxy-net

networks:
  nginx-proxy-net:
    external: true
